### ISSUE TITLE
Latex output missing, error while retrieving Latex.js

### ISSUE THREAD

**Issue by malte-j** [mkhan45/CalcuLaTeX-Web#4]
Latex.js is loaded using the wrong url:
![error](https://user-images.githubusercontent.com/12611076/109490598-b7a33700-7a88-11eb-8225-e68cd25bd10a.png)

**Comment by mkhan45** [comment]
Looks like the first error was causing the problem. The 2nd one is from a script which is actually autoloaded from latex.js but it's always been there.

This should be fixed in 73ec7d8
